# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox pytest isort ruff
        if [ -f requirements-dev.txt ]; then pip install -r requirements0-dev.txt; fi
    - name: Format with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        tox -e format
    - name: Lint with Ruff
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        tox -e lint
    - name: Test with pytest
      run: |
        pytest
